function CodeDefine() { 
this.def = new Array();
this.def["stopRequested"] = {file: "ert_main_cpp.html",line:35,type:"var"};
this.def["runModel"] = {file: "ert_main_cpp.html",line:36,type:"var"};
this.def["stopSem"] = {file: "ert_main_cpp.html",line:37,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_cpp.html",line:38,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_cpp.html",line:39,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_cpp.html",line:40,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_cpp.html",line:41,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_cpp.html",line:42,type:"var"};
this.def["baseRateTask"] = {file: "ert_main_cpp.html",line:43,type:"fcn"};
this.def["exitFcn"] = {file: "ert_main_cpp.html",line:60,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_cpp.html",line:67,type:"fcn"};
this.def["px4_simulink_app_task_main"] = {file: "ert_main_cpp.html",line:86,type:"fcn"};
this.def["px4demo_PWM_B"] = {file: "px4demo_PWM_cpp.html",line:23,type:"var"};
this.def["px4demo_PWM_DW"] = {file: "px4demo_PWM_cpp.html",line:26,type:"var"};
this.def["px4demo_PWM_M_"] = {file: "px4demo_PWM_cpp.html",line:29,type:"var"};
this.def["px4demo_PWM_M"] = {file: "px4demo_PWM_cpp.html",line:30,type:"var"};
this.def["px4demo_PWM.cpp:px4demo_PWM_SystemCore_setup"] = {file: "px4demo_PWM_cpp.html",line:37,type:"fcn"};
this.def["px4demo_PWM.cpp:px4demo_PWM_SystemCore_setup_m"] = {file: "px4demo_PWM_cpp.html",line:82,type:"fcn"};
this.def["px4demo_PWM_step"] = {file: "px4demo_PWM_cpp.html",line:128,type:"fcn"};
this.def["px4demo_PWM_initialize"] = {file: "px4demo_PWM_cpp.html",line:241,type:"fcn"};
this.def["px4demo_PWM_terminate"] = {file: "px4demo_PWM_cpp.html",line:280,type:"fcn"};
this.def["P_px4demo_PWM_T"] = {file: "px4demo_PWM_types_h.html",line:72,type:"type"};
this.def["RT_MODEL_px4demo_PWM_T"] = {file: "px4demo_PWM_types_h.html",line:75,type:"type"};
this.def["px4demo_PWM_P"] = {file: "px4demo_PWM_data_cpp.html",line:23,type:"var"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["ulonglong_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:85,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:90,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:95,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:102,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:109,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:116,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:123,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:130,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:137,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:144,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:151,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:172,type:"type"};
this.def["pwm_open"] = {file: "MW_PX4_PWM_cpp.html",line:168,type:"fcn"};
this.def["pwm_getServoCount"] = {file: "MW_PX4_PWM_cpp.html",line:202,type:"fcn"};
this.def["pwm_arm"] = {file: "MW_PX4_PWM_cpp.html",line:229,type:"fcn"};
this.def["pwm_disarm"] = {file: "MW_PX4_PWM_cpp.html",line:264,type:"fcn"};
this.def["pwm_setPWMRate"] = {file: "MW_PX4_PWM_cpp.html",line:290,type:"fcn"};
this.def["pwm_setChannelMask"] = {file: "MW_PX4_PWM_cpp.html",line:340,type:"fcn"};
this.def["pwm_setDisarmedPWM"] = {file: "MW_PX4_PWM_cpp.html",line:361,type:"fcn"};
this.def["pwm_setFailsafePWM"] = {file: "MW_PX4_PWM_cpp.html",line:456,type:"fcn"};
this.def["pwm_forceFailsafe"] = {file: "MW_PX4_PWM_cpp.html",line:519,type:"fcn"};
this.def["pwm_forceTerminateFailsafe"] = {file: "MW_PX4_PWM_cpp.html",line:540,type:"fcn"};
this.def["pwm_setServo"] = {file: "MW_PX4_PWM_cpp.html",line:561,type:"fcn"};
this.def["pwm_resetServo"] = {file: "MW_PX4_PWM_cpp.html",line:624,type:"fcn"};
this.def["pwm_close"] = {file: "MW_PX4_PWM_cpp.html",line:702,type:"fcn"};
this.def["getFSPWMValues"] = {file: "MW_PX4_PWM_cpp.html",line:720,type:"fcn"};
this.def["getDAPWMValues"] = {file: "MW_PX4_PWM_cpp.html",line:781,type:"fcn"};
this.def["addDelayOneshot"] = {file: "MW_PX4_PWM_cpp.html",line:842,type:"fcn"};
this.def["x"] = {file: "MW_PX4_TaskControl_cpp.html",line:56,type:"var"};
this.def["px4_app_usage"] = {file: "MW_PX4_TaskControl_cpp.html",line:60,type:"fcn"};
this.def["buffer"] = {file: "MW_PX4_TaskControl_cpp.html",line:68,type:"var"};
this.def["shell"] = {file: "MW_PX4_TaskControl_cpp.html",line:69,type:"var"};
this.def["shellWait"] = {file: "MW_PX4_TaskControl_cpp.html",line:70,type:"fcn"};
this.def["px4_simulink_app_stop_Crazyflie_modules"] = {file: "MW_PX4_TaskControl_cpp.html",line:85,type:"fcn"};
this.def["px4_simulink_app_control_MAVLink"] = {file: "MW_PX4_TaskControl_cpp.html",line:108,type:"fcn"};
this.def["px4_simulink_app_main"] = {file: "MW_PX4_TaskControl_cpp.html",line:128,type:"fcn"};
this.def["MW_PX4_Terminate"] = {file: "MW_PX4_TaskControl_cpp.html",line:224,type:"fcn"};
this.def["uORB_read_initialize"] = {file: "MW_uORB_Read_cpp.html",line:9,type:"fcn"};
this.def["uORB_read_step"] = {file: "MW_uORB_Read_cpp.html",line:18,type:"fcn"};
this.def["uORB_read_terminate"] = {file: "MW_uORB_Read_cpp.html",line:77,type:"fcn"};
this.def["px4_Bus_actuator_outputs"] = {file: "MW_uORB_busstruct_conversion_h.html",line:6,type:"type"};
this.def["attr"] = {file: "nuttxinitialize_cpp.html",line:17,type:"var"};
this.def["nuttxinitialize.cpp:g_info"] = {file: "nuttxinitialize_cpp.html",line:18,type:"var"};
this.def["g_sp"] = {file: "nuttxinitialize_cpp.html",line:19,type:"var"};
this.def["BaseRate_HRT"] = {file: "nuttxinitialize_cpp.html",line:25,type:"var"};
this.def["baserate_sem_copy"] = {file: "nuttxinitialize_cpp.html",line:26,type:"var"};
this.def["EXT_sig_info"] = {file: "nuttxinitialize_cpp.html",line:31,type:"var"};
this.def["SDCard_sig_info"] = {file: "nuttxinitialize_cpp.html",line:32,type:"var"};
this.def["setTaskPeriod"] = {file: "nuttxinitialize_cpp.html",line:37,type:"fcn"};
this.def["print_sem_value"] = {file: "nuttxinitialize_cpp.html",line:61,type:"fcn"};
this.def["nuttxinitialize.cpp:Base_HRT_Callback"] = {file: "nuttxinitialize_cpp.html",line:65,type:"fcn"};
this.def["myWaitForThisEvent"] = {file: "nuttxinitialize_cpp.html",line:89,type:"fcn"};
this.def["MW_PX4_WaitForThisEvent"] = {file: "nuttxinitialize_cpp.html",line:98,type:"fcn"};
this.def["myAddBlockForThisEvent"] = {file: "nuttxinitialize_cpp.html",line:123,type:"fcn"};
this.def["nuttxRTOSInit"] = {file: "nuttxinitialize_cpp.html",line:133,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_cpp.html"] = "../ert_main.cpp";
	this.html2Root["ert_main_cpp.html"] = "ert_main_cpp.html";
	this.html2SrcPath["px4demo_PWM_cpp.html"] = "../px4demo_PWM.cpp";
	this.html2Root["px4demo_PWM_cpp.html"] = "px4demo_PWM_cpp.html";
	this.html2SrcPath["px4demo_PWM_h.html"] = "../px4demo_PWM.h";
	this.html2Root["px4demo_PWM_h.html"] = "px4demo_PWM_h.html";
	this.html2SrcPath["px4demo_PWM_private_h.html"] = "../px4demo_PWM_private.h";
	this.html2Root["px4demo_PWM_private_h.html"] = "px4demo_PWM_private_h.html";
	this.html2SrcPath["px4demo_PWM_types_h.html"] = "../px4demo_PWM_types.h";
	this.html2Root["px4demo_PWM_types_h.html"] = "px4demo_PWM_types_h.html";
	this.html2SrcPath["px4demo_PWM_data_cpp.html"] = "../px4demo_PWM_data.cpp";
	this.html2Root["px4demo_PWM_data_cpp.html"] = "px4demo_PWM_data_cpp.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_PX4_PWM_cpp.html"] = "../../../../../../../ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/px4/src/MW_PX4_PWM.cpp";
	this.html2Root["MW_PX4_PWM_cpp.html"] = "MW_PX4_PWM_cpp.html";
	this.html2SrcPath["MW_PX4_TaskControl_cpp.html"] = "../../../../../../../ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/px4/src/MW_PX4_TaskControl.cpp";
	this.html2Root["MW_PX4_TaskControl_cpp.html"] = "MW_PX4_TaskControl_cpp.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["MW_uORB_Read_cpp.html"] = "../../../../../../../ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/px4/src/MW_uORB_Read.cpp";
	this.html2Root["MW_uORB_Read_cpp.html"] = "MW_uORB_Read_cpp.html";
	this.html2SrcPath["MW_uORB_busstruct_conversion_h.html"] = "../MW_uORB_busstruct_conversion.h";
	this.html2Root["MW_uORB_busstruct_conversion_h.html"] = "MW_uORB_busstruct_conversion_h.html";
	this.html2SrcPath["nuttxinitialize_cpp.html"] = "../../../../../../../ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/px4/src/nuttxinitialize.cpp";
	this.html2Root["nuttxinitialize_cpp.html"] = "nuttxinitialize_cpp.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_cpp.html","px4demo_PWM_cpp.html","px4demo_PWM_h.html","px4demo_PWM_private_h.html","px4demo_PWM_types_h.html","px4demo_PWM_data_cpp.html","rtwtypes_h.html","rtmodel_h.html","MW_PX4_PWM_cpp.html","MW_PX4_TaskControl_cpp.html","MW_custom_RTOS_header_h.html","MW_target_hardware_resources_h.html","MW_uORB_Read_cpp.html","MW_uORB_busstruct_conversion_h.html","nuttxinitialize_cpp.html"];
